//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project5.WeatherService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeatherReport", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class WeatherReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project5.WeatherService.DailyForecast[] dailyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double lonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timezoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timezone_offsetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project5.WeatherService.DailyForecast[] daily {
            get {
                return this.dailyField;
            }
            set {
                if ((object.ReferenceEquals(this.dailyField, value) != true)) {
                    this.dailyField = value;
                    this.RaisePropertyChanged("daily");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lat {
            get {
                return this.latField;
            }
            set {
                if ((this.latField.Equals(value) != true)) {
                    this.latField = value;
                    this.RaisePropertyChanged("lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lon {
            get {
                return this.lonField;
            }
            set {
                if ((this.lonField.Equals(value) != true)) {
                    this.lonField = value;
                    this.RaisePropertyChanged("lon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string timezone {
            get {
                return this.timezoneField;
            }
            set {
                if ((object.ReferenceEquals(this.timezoneField, value) != true)) {
                    this.timezoneField = value;
                    this.RaisePropertyChanged("timezone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string timezone_offset {
            get {
                return this.timezone_offsetField;
            }
            set {
                if ((object.ReferenceEquals(this.timezone_offsetField, value) != true)) {
                    this.timezone_offsetField = value;
                    this.RaisePropertyChanged("timezone_offset");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DailyForecast", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class DailyForecast : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double cloudsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double degField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dew_pointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project5.WeatherService.FeelsLike feelsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double humidityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double popField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double pressureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double speedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sunriseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sunsetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project5.WeatherService.TempInfo tempField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double uviField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project5.WeatherService.Weather[] weatherField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double clouds {
            get {
                return this.cloudsField;
            }
            set {
                if ((this.cloudsField.Equals(value) != true)) {
                    this.cloudsField = value;
                    this.RaisePropertyChanged("clouds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double deg {
            get {
                return this.degField;
            }
            set {
                if ((this.degField.Equals(value) != true)) {
                    this.degField = value;
                    this.RaisePropertyChanged("deg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double dew_point {
            get {
                return this.dew_pointField;
            }
            set {
                if ((this.dew_pointField.Equals(value) != true)) {
                    this.dew_pointField = value;
                    this.RaisePropertyChanged("dew_point");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dt {
            get {
                return this.dtField;
            }
            set {
                if ((object.ReferenceEquals(this.dtField, value) != true)) {
                    this.dtField = value;
                    this.RaisePropertyChanged("dt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project5.WeatherService.FeelsLike feels {
            get {
                return this.feelsField;
            }
            set {
                if ((object.ReferenceEquals(this.feelsField, value) != true)) {
                    this.feelsField = value;
                    this.RaisePropertyChanged("feels");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double humidity {
            get {
                return this.humidityField;
            }
            set {
                if ((this.humidityField.Equals(value) != true)) {
                    this.humidityField = value;
                    this.RaisePropertyChanged("humidity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double pop {
            get {
                return this.popField;
            }
            set {
                if ((this.popField.Equals(value) != true)) {
                    this.popField = value;
                    this.RaisePropertyChanged("pop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double pressure {
            get {
                return this.pressureField;
            }
            set {
                if ((this.pressureField.Equals(value) != true)) {
                    this.pressureField = value;
                    this.RaisePropertyChanged("pressure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double speed {
            get {
                return this.speedField;
            }
            set {
                if ((this.speedField.Equals(value) != true)) {
                    this.speedField = value;
                    this.RaisePropertyChanged("speed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sunrise {
            get {
                return this.sunriseField;
            }
            set {
                if ((object.ReferenceEquals(this.sunriseField, value) != true)) {
                    this.sunriseField = value;
                    this.RaisePropertyChanged("sunrise");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sunset {
            get {
                return this.sunsetField;
            }
            set {
                if ((object.ReferenceEquals(this.sunsetField, value) != true)) {
                    this.sunsetField = value;
                    this.RaisePropertyChanged("sunset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project5.WeatherService.TempInfo temp {
            get {
                return this.tempField;
            }
            set {
                if ((object.ReferenceEquals(this.tempField, value) != true)) {
                    this.tempField = value;
                    this.RaisePropertyChanged("temp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double uvi {
            get {
                return this.uviField;
            }
            set {
                if ((this.uviField.Equals(value) != true)) {
                    this.uviField = value;
                    this.RaisePropertyChanged("uvi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project5.WeatherService.Weather[] weather {
            get {
                return this.weatherField;
            }
            set {
                if ((object.ReferenceEquals(this.weatherField, value) != true)) {
                    this.weatherField = value;
                    this.RaisePropertyChanged("weather");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeelsLike", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class FeelsLike : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double evenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double mornField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double day {
            get {
                return this.dayField;
            }
            set {
                if ((this.dayField.Equals(value) != true)) {
                    this.dayField = value;
                    this.RaisePropertyChanged("day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double even {
            get {
                return this.evenField;
            }
            set {
                if ((this.evenField.Equals(value) != true)) {
                    this.evenField = value;
                    this.RaisePropertyChanged("even");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double morn {
            get {
                return this.mornField;
            }
            set {
                if ((this.mornField.Equals(value) != true)) {
                    this.mornField = value;
                    this.RaisePropertyChanged("morn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double night {
            get {
                return this.nightField;
            }
            set {
                if ((this.nightField.Equals(value) != true)) {
                    this.nightField = value;
                    this.RaisePropertyChanged("night");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TempInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class TempInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double dayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double eveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double maxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double minField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double mornField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double day {
            get {
                return this.dayField;
            }
            set {
                if ((this.dayField.Equals(value) != true)) {
                    this.dayField = value;
                    this.RaisePropertyChanged("day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double eve {
            get {
                return this.eveField;
            }
            set {
                if ((this.eveField.Equals(value) != true)) {
                    this.eveField = value;
                    this.RaisePropertyChanged("eve");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double max {
            get {
                return this.maxField;
            }
            set {
                if ((this.maxField.Equals(value) != true)) {
                    this.maxField = value;
                    this.RaisePropertyChanged("max");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double min {
            get {
                return this.minField;
            }
            set {
                if ((this.minField.Equals(value) != true)) {
                    this.minField = value;
                    this.RaisePropertyChanged("min");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double morn {
            get {
                return this.mornField;
            }
            set {
                if ((this.mornField.Equals(value) != true)) {
                    this.mornField = value;
                    this.RaisePropertyChanged("morn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double night {
            get {
                return this.nightField;
            }
            set {
                if ((this.nightField.Equals(value) != true)) {
                    this.nightField = value;
                    this.RaisePropertyChanged("night");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Weather", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Weather : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mainField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string icon {
            get {
                return this.iconField;
            }
            set {
                if ((object.ReferenceEquals(this.iconField, value) != true)) {
                    this.iconField = value;
                    this.RaisePropertyChanged("icon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string main {
            get {
                return this.mainField;
            }
            set {
                if ((object.ReferenceEquals(this.mainField, value) != true)) {
                    this.mainField = value;
                    this.RaisePropertyChanged("main");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeatherService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetForecast", ReplyAction="http://tempuri.org/IService/GetForecastResponse")]
        string[] GetForecast();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetForecast", ReplyAction="http://tempuri.org/IService/GetForecastResponse")]
        System.Threading.Tasks.Task<string[]> GetForecastAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetWeatherReport", ReplyAction="http://tempuri.org/IService/GetWeatherReportResponse")]
        Project5.WeatherService.WeatherReport GetWeatherReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetWeatherReport", ReplyAction="http://tempuri.org/IService/GetWeatherReportResponse")]
        System.Threading.Tasks.Task<Project5.WeatherService.WeatherReport> GetWeatherReportAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TodayForecast", ReplyAction="http://tempuri.org/IService/TodayForecastResponse")]
        string TodayForecast(Project5.WeatherService.DailyForecast[] todayReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TodayForecast", ReplyAction="http://tempuri.org/IService/TodayForecastResponse")]
        System.Threading.Tasks.Task<string> TodayForecastAsync(Project5.WeatherService.DailyForecast[] todayReport);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Project5.WeatherService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Project5.WeatherService.IService>, Project5.WeatherService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetForecast() {
            return base.Channel.GetForecast();
        }
        
        public System.Threading.Tasks.Task<string[]> GetForecastAsync() {
            return base.Channel.GetForecastAsync();
        }
        
        public Project5.WeatherService.WeatherReport GetWeatherReport() {
            return base.Channel.GetWeatherReport();
        }
        
        public System.Threading.Tasks.Task<Project5.WeatherService.WeatherReport> GetWeatherReportAsync() {
            return base.Channel.GetWeatherReportAsync();
        }
        
        public string TodayForecast(Project5.WeatherService.DailyForecast[] todayReport) {
            return base.Channel.TodayForecast(todayReport);
        }
        
        public System.Threading.Tasks.Task<string> TodayForecastAsync(Project5.WeatherService.DailyForecast[] todayReport) {
            return base.Channel.TodayForecastAsync(todayReport);
        }
    }
}
