//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project5.StockBuildAndQuote {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockBuildAndQuote.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/stockBuild", ReplyAction="http://tempuri.org/IService/stockBuildResponse")]
        string stockBuild();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/stockBuild", ReplyAction="http://tempuri.org/IService/stockBuildResponse")]
        System.Threading.Tasks.Task<string> stockBuildAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/stockQuote", ReplyAction="http://tempuri.org/IService/stockQuoteResponse")]
        string stockQuote(string stockSymbol, string stockQuotePairsFilePat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/stockQuote", ReplyAction="http://tempuri.org/IService/stockQuoteResponse")]
        System.Threading.Tasks.Task<string> stockQuoteAsync(string stockSymbol, string stockQuotePairsFilePat);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Project5.StockBuildAndQuote.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Project5.StockBuildAndQuote.IService>, Project5.StockBuildAndQuote.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string stockBuild() {
            return base.Channel.stockBuild();
        }
        
        public System.Threading.Tasks.Task<string> stockBuildAsync() {
            return base.Channel.stockBuildAsync();
        }
        
        public string stockQuote(string stockSymbol, string stockQuotePairsFilePat) {
            return base.Channel.stockQuote(stockSymbol, stockQuotePairsFilePat);
        }
        
        public System.Threading.Tasks.Task<string> stockQuoteAsync(string stockSymbol, string stockQuotePairsFilePat) {
            return base.Channel.stockQuoteAsync(stockSymbol, stockQuotePairsFilePat);
        }
    }
}
